[project]
name = "storm-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.11",
    "mcp>=1.3.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
]
